App.comment = App.cabel.subscriptions.create 'CommentChannel',
  connected: ->
    alert("newnewnewne");
# Called when the subscription is ready for use on the server
    return
  disconnected: ->
# Called when the subscription has been terminated by the server
    return
  received: (data) ->
# Called when there's incoming data on the websocket for this channel
    return

# ---
# generated by js2coffee 2.2.0